'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.6421
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=2.0.50727.6421.
'
Namespace mx.advans.app
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="advanswsdlBinding", [Namespace]:="urn:advanswsdl")>  _
    Partial Public Class advanswsdl
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private timbrarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private timbrar2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private timbrar3OperationCompleted As System.Threading.SendOrPostCallback
        
        Private cancelarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private cancelarPFXSyncOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultar2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultar_cfdiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultar_horaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.FacturaNET.My.MySettings.Default.FacturaNET_mx_advans_app_advanswsdl
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event timbrarCompleted As timbrarCompletedEventHandler
        
        '''<remarks/>
        Public Event timbrar2Completed As timbrar2CompletedEventHandler
        
        '''<remarks/>
        Public Event timbrar3Completed As timbrar3CompletedEventHandler
        
        '''<remarks/>
        Public Event cancelarCompleted As cancelarCompletedEventHandler
        
        '''<remarks/>
        Public Event cancelarPFXSyncCompleted As cancelarPFXSyncCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarCompleted As consultarCompletedEventHandler
        
        '''<remarks/>
        Public Event consultar2Completed As consultar2CompletedEventHandler
        
        '''<remarks/>
        Public Event consultar_cfdiCompleted As consultar_cfdiCompletedEventHandler
        
        '''<remarks/>
        Public Event consultar_horaCompleted As consultar_horaCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:advanswsdl#timbrar", RequestNamespace:="urn:advanswsdl", ResponseNamespace:="urn:advanswsdl")>  _
        Public Function timbrar(ByVal credential As String, ByVal cfdi As String) As <System.Xml.Serialization.SoapElementAttribute("return")> RespuestaTimbre
            Dim results() As Object = Me.Invoke("timbrar", New Object() {credential, cfdi})
            Return CType(results(0),RespuestaTimbre)
        End Function
        
        '''<remarks/>
        Public Overloads Sub timbrarAsync(ByVal credential As String, ByVal cfdi As String)
            Me.timbrarAsync(credential, cfdi, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub timbrarAsync(ByVal credential As String, ByVal cfdi As String, ByVal userState As Object)
            If (Me.timbrarOperationCompleted Is Nothing) Then
                Me.timbrarOperationCompleted = AddressOf Me.OntimbrarOperationCompleted
            End If
            Me.InvokeAsync("timbrar", New Object() {credential, cfdi}, Me.timbrarOperationCompleted, userState)
        End Sub
        
        Private Sub OntimbrarOperationCompleted(ByVal arg As Object)
            If (Not (Me.timbrarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent timbrarCompleted(Me, New timbrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:advanswsdl#timbrar", RequestNamespace:="urn:advanswsdl", ResponseNamespace:="urn:advanswsdl")>  _
        Public Function timbrar2(ByVal credential As String, ByVal cfdi As String) As <System.Xml.Serialization.SoapElementAttribute("return")> RespuestaTimbre2
            Dim results() As Object = Me.Invoke("timbrar2", New Object() {credential, cfdi})
            Return CType(results(0),RespuestaTimbre2)
        End Function
        
        '''<remarks/>
        Public Overloads Sub timbrar2Async(ByVal credential As String, ByVal cfdi As String)
            Me.timbrar2Async(credential, cfdi, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub timbrar2Async(ByVal credential As String, ByVal cfdi As String, ByVal userState As Object)
            If (Me.timbrar2OperationCompleted Is Nothing) Then
                Me.timbrar2OperationCompleted = AddressOf Me.Ontimbrar2OperationCompleted
            End If
            Me.InvokeAsync("timbrar2", New Object() {credential, cfdi}, Me.timbrar2OperationCompleted, userState)
        End Sub
        
        Private Sub Ontimbrar2OperationCompleted(ByVal arg As Object)
            If (Not (Me.timbrar2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent timbrar2Completed(Me, New timbrar2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:advanswsdl#timbrar", RequestNamespace:="urn:advanswsdl", ResponseNamespace:="urn:advanswsdl")>  _
        Public Function timbrar3(ByVal credential As String, ByVal cfdi As String) As <System.Xml.Serialization.SoapElementAttribute("return")> RespuestaTimbre
            Dim results() As Object = Me.Invoke("timbrar3", New Object() {credential, cfdi})
            Return CType(results(0),RespuestaTimbre)
        End Function
        
        '''<remarks/>
        Public Overloads Sub timbrar3Async(ByVal credential As String, ByVal cfdi As String)
            Me.timbrar3Async(credential, cfdi, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub timbrar3Async(ByVal credential As String, ByVal cfdi As String, ByVal userState As Object)
            If (Me.timbrar3OperationCompleted Is Nothing) Then
                Me.timbrar3OperationCompleted = AddressOf Me.Ontimbrar3OperationCompleted
            End If
            Me.InvokeAsync("timbrar3", New Object() {credential, cfdi}, Me.timbrar3OperationCompleted, userState)
        End Sub
        
        Private Sub Ontimbrar3OperationCompleted(ByVal arg As Object)
            If (Not (Me.timbrar3CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent timbrar3Completed(Me, New timbrar3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:advanswsdl#cancelar", RequestNamespace:="urn:advanswsdl", ResponseNamespace:="urn:advanswsdl")>  _
        Public Function cancelar(ByVal credential As String, ByVal rfc_emisor As String, ByVal uuid As String, ByVal key As String, ByVal cer As String) As <System.Xml.Serialization.SoapElementAttribute("return")> RespuestaCancelacion
            Dim results() As Object = Me.Invoke("cancelar", New Object() {credential, rfc_emisor, uuid, key, cer})
            Return CType(results(0),RespuestaCancelacion)
        End Function
        
        '''<remarks/>
        Public Overloads Sub cancelarAsync(ByVal credential As String, ByVal rfc_emisor As String, ByVal uuid As String, ByVal key As String, ByVal cer As String)
            Me.cancelarAsync(credential, rfc_emisor, uuid, key, cer, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub cancelarAsync(ByVal credential As String, ByVal rfc_emisor As String, ByVal uuid As String, ByVal key As String, ByVal cer As String, ByVal userState As Object)
            If (Me.cancelarOperationCompleted Is Nothing) Then
                Me.cancelarOperationCompleted = AddressOf Me.OncancelarOperationCompleted
            End If
            Me.InvokeAsync("cancelar", New Object() {credential, rfc_emisor, uuid, key, cer}, Me.cancelarOperationCompleted, userState)
        End Sub
        
        Private Sub OncancelarOperationCompleted(ByVal arg As Object)
            If (Not (Me.cancelarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cancelarCompleted(Me, New cancelarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:advanswsdl#cancelarPFXSync", RequestNamespace:="urn:advanswsdl", ResponseNamespace:="urn:advanswsdl")>  _
        Public Function cancelarPFXSync(ByVal credential As String, ByVal rfc_emisor As String, ByVal uuid As String, ByVal pfx As String, ByVal pfx_password As String) As <System.Xml.Serialization.SoapElementAttribute("return")> RespuestaCancelacion
            Dim results() As Object = Me.Invoke("cancelarPFXSync", New Object() {credential, rfc_emisor, uuid, pfx, pfx_password})
            Return CType(results(0),RespuestaCancelacion)
        End Function
        
        '''<remarks/>
        Public Overloads Sub cancelarPFXSyncAsync(ByVal credential As String, ByVal rfc_emisor As String, ByVal uuid As String, ByVal pfx As String, ByVal pfx_password As String)
            Me.cancelarPFXSyncAsync(credential, rfc_emisor, uuid, pfx, pfx_password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub cancelarPFXSyncAsync(ByVal credential As String, ByVal rfc_emisor As String, ByVal uuid As String, ByVal pfx As String, ByVal pfx_password As String, ByVal userState As Object)
            If (Me.cancelarPFXSyncOperationCompleted Is Nothing) Then
                Me.cancelarPFXSyncOperationCompleted = AddressOf Me.OncancelarPFXSyncOperationCompleted
            End If
            Me.InvokeAsync("cancelarPFXSync", New Object() {credential, rfc_emisor, uuid, pfx, pfx_password}, Me.cancelarPFXSyncOperationCompleted, userState)
        End Sub
        
        Private Sub OncancelarPFXSyncOperationCompleted(ByVal arg As Object)
            If (Not (Me.cancelarPFXSyncCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cancelarPFXSyncCompleted(Me, New cancelarPFXSyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:advanswsdl#consulta", RequestNamespace:="urn:advanswsdl", ResponseNamespace:="urn:advanswsdl")>  _
        Public Function consultar(ByVal credential As String, ByVal uuid As String) As <System.Xml.Serialization.SoapElementAttribute("return")> RespuestaConsulta
            Dim results() As Object = Me.Invoke("consultar", New Object() {credential, uuid})
            Return CType(results(0),RespuestaConsulta)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarAsync(ByVal credential As String, ByVal uuid As String)
            Me.consultarAsync(credential, uuid, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarAsync(ByVal credential As String, ByVal uuid As String, ByVal userState As Object)
            If (Me.consultarOperationCompleted Is Nothing) Then
                Me.consultarOperationCompleted = AddressOf Me.OnconsultarOperationCompleted
            End If
            Me.InvokeAsync("consultar", New Object() {credential, uuid}, Me.consultarOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarCompleted(Me, New consultarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:advanswsdl#consulta2", RequestNamespace:="urn:advanswsdl", ResponseNamespace:="urn:advanswsdl")>  _
        Public Function consultar2(ByVal credential As String, ByVal rfc_emisor As String, ByVal rfc_receptor As String, ByVal serie As String, ByVal folio As String) As <System.Xml.Serialization.SoapElementAttribute("return")> RespuestaConsulta
            Dim results() As Object = Me.Invoke("consultar2", New Object() {credential, rfc_emisor, rfc_receptor, serie, folio})
            Return CType(results(0),RespuestaConsulta)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultar2Async(ByVal credential As String, ByVal rfc_emisor As String, ByVal rfc_receptor As String, ByVal serie As String, ByVal folio As String)
            Me.consultar2Async(credential, rfc_emisor, rfc_receptor, serie, folio, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultar2Async(ByVal credential As String, ByVal rfc_emisor As String, ByVal rfc_receptor As String, ByVal serie As String, ByVal folio As String, ByVal userState As Object)
            If (Me.consultar2OperationCompleted Is Nothing) Then
                Me.consultar2OperationCompleted = AddressOf Me.Onconsultar2OperationCompleted
            End If
            Me.InvokeAsync("consultar2", New Object() {credential, rfc_emisor, rfc_receptor, serie, folio}, Me.consultar2OperationCompleted, userState)
        End Sub
        
        Private Sub Onconsultar2OperationCompleted(ByVal arg As Object)
            If (Not (Me.consultar2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultar2Completed(Me, New consultar2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:advanswsdl#consulta", RequestNamespace:="urn:advanswsdl", ResponseNamespace:="urn:advanswsdl")>  _
        Public Function consultar_cfdi(ByVal credential As String, ByVal uuid As String) As <System.Xml.Serialization.SoapElementAttribute("return")> RespuestaConsulta
            Dim results() As Object = Me.Invoke("consultar_cfdi", New Object() {credential, uuid})
            Return CType(results(0),RespuestaConsulta)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultar_cfdiAsync(ByVal credential As String, ByVal uuid As String)
            Me.consultar_cfdiAsync(credential, uuid, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultar_cfdiAsync(ByVal credential As String, ByVal uuid As String, ByVal userState As Object)
            If (Me.consultar_cfdiOperationCompleted Is Nothing) Then
                Me.consultar_cfdiOperationCompleted = AddressOf Me.Onconsultar_cfdiOperationCompleted
            End If
            Me.InvokeAsync("consultar_cfdi", New Object() {credential, uuid}, Me.consultar_cfdiOperationCompleted, userState)
        End Sub
        
        Private Sub Onconsultar_cfdiOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultar_cfdiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultar_cfdiCompleted(Me, New consultar_cfdiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:advanswsdl#consultaHora", RequestNamespace:="urn:advanswsdl", ResponseNamespace:="urn:advanswsdl")>  _
        Public Function consultar_hora() As <System.Xml.Serialization.SoapElementAttribute("return")> RespuestaConsultaHora
            Dim results() As Object = Me.Invoke("consultar_hora", New Object(-1) {})
            Return CType(results(0),RespuestaConsultaHora)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultar_horaAsync()
            Me.consultar_horaAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultar_horaAsync(ByVal userState As Object)
            If (Me.consultar_horaOperationCompleted Is Nothing) Then
                Me.consultar_horaOperationCompleted = AddressOf Me.Onconsultar_horaOperationCompleted
            End If
            Me.InvokeAsync("consultar_hora", New Object(-1) {}, Me.consultar_horaOperationCompleted, userState)
        End Sub
        
        Private Sub Onconsultar_horaOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultar_horaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultar_horaCompleted(Me, New consultar_horaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6421"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:advanswsdl")>  _
    Partial Public Class RespuestaTimbre
        
        Private codeField As String
        
        Private subCodeField As String
        
        Private messageField As String
        
        Private timbreField As String
        
        '''<comentarios/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SubCode() As String
            Get
                Return Me.subCodeField
            End Get
            Set
                Me.subCodeField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Timbre() As String
            Get
                Return Me.timbreField
            End Get
            Set
                Me.timbreField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6421"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:advanswsdl")>  _
    Partial Public Class RespuestaConsultaHora
        
        Private horaField As String
        
        '''<comentarios/>
        Public Property Hora() As String
            Get
                Return Me.horaField
            End Get
            Set
                Me.horaField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6421"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:advanswsdl")>  _
    Partial Public Class RespuestaConsulta
        
        Private codeField As String
        
        Private subCodeField As String
        
        Private messageField As String
        
        Private acuseField As String
        
        '''<comentarios/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SubCode() As String
            Get
                Return Me.subCodeField
            End Get
            Set
                Me.subCodeField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Acuse() As String
            Get
                Return Me.acuseField
            End Get
            Set
                Me.acuseField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6421"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:advanswsdl")>  _
    Partial Public Class RespuestaCancelacion
        
        Private codeField As String
        
        Private subCodeField As String
        
        Private messageField As String
        
        Private acuseField As String
        
        '''<comentarios/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SubCode() As String
            Get
                Return Me.subCodeField
            End Get
            Set
                Me.subCodeField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Acuse() As String
            Get
                Return Me.acuseField
            End Get
            Set
                Me.acuseField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.6421"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:advanswsdl")>  _
    Partial Public Class RespuestaTimbre2
        
        Private codeField As String
        
        Private subCodeField As String
        
        Private messageField As String
        
        Private cFDIField As String
        
        '''<comentarios/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property SubCode() As String
            Get
                Return Me.subCodeField
            End Get
            Set
                Me.subCodeField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property CFDI() As String
            Get
                Return Me.cFDIField
            End Get
            Set
                Me.cFDIField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")>  _
    Public Delegate Sub timbrarCompletedEventHandler(ByVal sender As Object, ByVal e As timbrarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class timbrarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaTimbre
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaTimbre)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")>  _
    Public Delegate Sub timbrar2CompletedEventHandler(ByVal sender As Object, ByVal e As timbrar2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class timbrar2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaTimbre2
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaTimbre2)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")>  _
    Public Delegate Sub timbrar3CompletedEventHandler(ByVal sender As Object, ByVal e As timbrar3CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class timbrar3CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaTimbre
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaTimbre)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")>  _
    Public Delegate Sub cancelarCompletedEventHandler(ByVal sender As Object, ByVal e As cancelarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class cancelarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaCancelacion
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaCancelacion)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")>  _
    Public Delegate Sub cancelarPFXSyncCompletedEventHandler(ByVal sender As Object, ByVal e As cancelarPFXSyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class cancelarPFXSyncCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaCancelacion
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaCancelacion)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")>  _
    Public Delegate Sub consultarCompletedEventHandler(ByVal sender As Object, ByVal e As consultarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaConsulta
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaConsulta)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")>  _
    Public Delegate Sub consultar2CompletedEventHandler(ByVal sender As Object, ByVal e As consultar2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultar2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaConsulta
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaConsulta)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")>  _
    Public Delegate Sub consultar_cfdiCompletedEventHandler(ByVal sender As Object, ByVal e As consultar_cfdiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultar_cfdiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaConsulta
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaConsulta)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387")>  _
    Public Delegate Sub consultar_horaCompletedEventHandler(ByVal sender As Object, ByVal e As consultar_horaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.6387"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultar_horaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As RespuestaConsultaHora
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),RespuestaConsultaHora)
            End Get
        End Property
    End Class
End Namespace
